### ISSUE TITLE
I have file an error bug yesterday with Patrick, saying that despite that I have 3 statements with oevr 30 participants, hundreds of votes (more than 7 votes per parrticiapnt).  i cannot produce a report.

### ISSUE THREAD

**Issue by Tonyczar** [g0v-network/polis#4]
**Expected behavior**:
Please describe the expected behavior here.

**Actual behavior**:
Please describe the actual behavior here.

**To Reproduce**:
Please list detailed steps to reproduce here.

**Screenshots**:

**Device information**:
Please list any device details here.

**Additional context**:
Add any other context about the problem here which might be helpful.

**Comment by Tonyczar** [comment]
[Test Polis.docx](https://github.com/g0v-network/polis/files/6720486/Test.Polis.docx)

Here is a set of screeshots

**Comment by patcon** [comment]
Hi Tony,

Sorry, this is simply a fork of the main code repository, and not the main repository. No one from the core project team will see it here. I'm sensing you're unfamiliar with GitHub, and I am not an official resource (just another fan), and so I would suggest you contact hello@compdemocracy.org

If you'd like to try created a GitHub issue again, this is the right place: https://github.com/compdemocracy/polis/issues/choose

(Another bit of GitHub etiquette: I suggest you fill out any details that the template asks for, as that is often considered a show of good faith when asking for support. Ignoring the template's prompts tends to reflect poorly, and often makes maintainers less likely to expend energy supporting you.)

Sorry for the run-around and learning curves here :)

**Comment by Tonyczar** [comment]
Thank you, Patrick. The error has been resolved by Chris Small (thanks again Chris). 

 

I will certainly be back with something more challenging…

 

Regards

 

Tony

 

Tony Czarnecki
